Metrics/LineLength:
  Max: 80

Layout/HashAlignment:
  EnforcedColonStyle:
    - key
    - table
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
